
#ifndef WEMOSWEATHERSIMPLE_CONFIG_H
#define WEMOSWEATHERSIMPLE_CONFIG_H

#include "secrets.h"

//#define SUPPORT_ADAFRUIT_IO
#undef SUPPORT_ADAFRUIT_IO

#define SUPPORT_BLYNK
//#undef SUPPORT_BLYNK

#define SUPPORT_MQTT
//#undef SUPPORT_MQTT

//#define DEEP_SLEEP
#undef DEEP_SLEEP

#endif //WEMOSWEATHERSIMPLE_CONFIG_H
