#ifndef WEMOSWEATHERSIMPLE_SECRETS_H
#define WEMOSWEATHERSIMPLE_SECRETS_H

#define SECRET_BLYNK_TOKEN "token"
#define SECRET_WIFI_SSID "ssid"
#define SECRET_WIFI_PASS "pass"

#endif //WEMOSWEATHERSIMPLE_SECRETS_H
