#ifndef WEMOSWEATHERSIMPLE_SECRETS_H
#define WEMOSWEATHERSIMPLE_SECRETS_H

#define SECRET_BLYNK_TOKEN "token"
#define SECRET_WIFI_SSID "ssid"
#define SECRET_WIFI_PASS "pass"

#define SECRET_AIO_USERNAME "username"
#define SECRET_AIO_TOKEN "token"

#define SECRET_MQTT_USERNAME "user"
#define SECRET_MQTT_PASSWORD "pass"
#define SECRET_MQTT_SERVER "server"

#endif //WEMOSWEATHERSIMPLE_SECRETS_H
